/** Helper package with escape codes for terminal colors */
export const Colors = {
	red: (text: unknown) => `\x1b[31m${text}\x1b[0m`,
	green: (text: unknown) => `\x1b[32m${text}\x1b[0m`,
	yellow: (text: unknown) => `\x1b[33m${text}\x1b[0m`,
	blue: (text: unknown) => `\x1b[34m${text}\x1b[0m`,
	magenta: (text: unknown) => `\x1b[35m${text}\x1b[0m`,
	cyan: (text: unknown) => `\x1b[36m${text}\x1b[0m`,
	white: (text: unknown) => `\x1b[37m${text}\x1b[0m`,
	black: (text: unknown) => `\x1b[90m${text}\x1b[0m`,
	bgRed: (text: unknown) => `\x1b[41m${text}\x1b[0m`,
	bgGreen: (text: unknown) => `\x1b[42m${text}\x1b[0m`,
	bgYellow: (text: unknown) => `\x1b[43m${text}\x1b[0m`,
	bgBlue: (text: unknown) => `\x1b[44m${text}\x1b[0m`,
	bgMagenta: (text: unknown) => `\x1b[45m${text}\x1b[0m`,
	bgCyan: (text: unknown) => `\x1b[46m${text}\x1b[0m`,
	bgWhite: (text: unknown) => `\x1b[47m${text}\x1b[0m`,
	bgBlack: (text: unknown) => `\x1b[100m${text}\x1b[0m`,
	bold: (text: unknown) => `\x1b[1m${text}\x1b[0m`,
	dim: (text: unknown) => `\x1b[2m${text}\x1b[0m`,
	underline: (text: unknown) => `\x1b[4m${text}\x1b[0m`,
	invert: (text: unknown) => `\x1b[7m${text}\x1b[0m`,
	blink: (text: unknown) => `\x1b[5m${text}\x1b[0m`,
	hidden: (text: unknown) => `\x1b[8m${text}\x1b[0m`,
	strike: (text: unknown) => `\x1b[9m${text}\x1b[0m`,
};
